export const tableData = [
  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },
  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },

  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },
  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },
  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },
  {
    id: 1,
    firstName: 'Ахатджанов  ',
    lastName: 'Даниел',
    email: 'syimyk@gmail.com',
    phoneNumber: '+996 704 41 40 42',
    total: 9000000,
    url: 'src/assets/icon/Gogle.svg',
  },
];
